### ISSUE TITLE
Get events as Observable

### ISSUE THREAD

**Issue by asgerhallas** [Microsoft/serilog-sinks-testcorrelator#49]
We sometimes use log events to test things like error and retry patterns in long running background tasks. To make such tests reliable, we often use an observable stream of log messages to await a certain log event (or pattern of log events) before ending the test. 

We could really use a way to get a correlated log event stream as an IObservable from the TestCorrelator. I wonder if this is a feature you would want in this library, and if you would be interested in a pull request for it?

**Comment by MitchBodmer** [comment]
Hey @asgerhallas just wanted to let you know that I've seen this and I like the idea at first glance. I'll reply with a more thoughtful comment when I get a little time. Thanks!

**Comment by MitchBodmer** [comment]
I think this could work very nicely. Help me reason this out. I'm not an Rx expert by any stretch, but I've played around in the area a bit.

Just thinking out loud here.

1. The streams in this case would never produce an "OnCompleted" notification since there is no good way of determining if additional log events will be produced inside a context. Tasks within the context can be started at any time, even after the context has been disposed. I don't think that is necessarily a problem, but it's worth noting.

2. I think we can do this by creating a single stream of all log events written to the TestCorrelator and then returning filtered versions of that stream when the corresponding methods are called.

3. There are  two ways of correlating log events at the moment, I think we can create a good observable analog of both.

   - Log events with a specific correlation ID.

        ```csharp
        IObservable<LogEvent> TestCorrelator.GetLogEventsStreamFromContextGuid(Guid contextGuid)
        ```

        We just return a stream filtered on log events decorated with the provided context GUID. Simple enough.

   - Log events within the current context.

        ```csharp
        IObservable<LogEvent> TestCorrelator.GetLogEventsStreamFromCurrentContext()
        ```

        This is the same thing, but you filter based on the current context GUIDs.

    I'm not sure about either of those names.

4. The way I've described it would make these hot observables. That way it gives you the flexibility to get all or part of the log events depending on when you subscribe. If you want all of them up until that moment you can just use the Enumerable version anyway.

P.S. You can probably work around this by polling GetLogEventsFromContextGuid in the meantime. Not ideal obviously.

**Comment by asgerhallas** [comment]
Thanks a lot for the response. This aligns very much, with what I had in mind. Regarding number 4 though, I think it would be useful to have all the cold events prepended on subscribe and then transition to a hot after that. It makes it a little easier to maintain arrange/act/assert order, if you can subscribe after act - and often the rx query works as an assert in it self (given a timeout).

Would you like me to take a stab at it?

**Comment by asgerhallas** [comment]
@MitchBodmer would you like a PR for this? :)

**Comment by MitchBodmer** [comment]
Hey sorry! I actually have a first attempt at this already. It looks like there have been some new restrictions on the way I can publish packages since I last released, so it might be a few more days before I can get it out on the feed. I also discovered an unrelated bug with the existing methods so I'll include that fix.

I think you could achieve what you want with the hot observable and a ```Replay``` Rx operator or a ```ReplaySubject```.

My deeper reasoning for designing it as a hot observable is that hot observables "close over" their emitters and cold observables "create" their emitters generally. Since here the root emitter is the logger writing to the TestCorrelator, the stream we're creating is essentially a subject sitting between the logger and the subscriber and subjects are always hot.

I think there is also a possible use case where people will want the observables they get to accurately reflect the timing of log events as the come in. Say for example you're logging to a rate limited document database in production and want to ensure that some section of your code doesn't exceed a certain number of log events per second. If all previously emitted events were emitted immediately upon every subscription, you couldn't use something like TimeInterval to assert that.

You may also want to only subscribe after a certain time has elapsed, or after a certain event has occurred. In that case, you would have to filter out all log events prior to the area of interest if all log events were returned regardless of when you subscribed.

**Comment by asgerhallas** [comment]
Great news! Those are good reasons to go with hot observables, I must agree that this is the better design.

I look forward to trying it out.

**Comment by MitchBodmer** [comment]
@asgerhallas I'm still waiting on some issues with publishing, but in the mean time you can download the new package from the AppVeyor build [here](https://ci.appveyor.com/project/SerilogUtilitiesConcurrentCorrelatorSA/serilog-utilities-concurrent-correlator/branch/master/artifacts).

**Comment by asgerhallas** [comment]
@MitchBodmer I just went down this same road in a new code base many years later. Just wanted to thank you for making it :)
